name: Update Build Date

on:
  push:
    branches:
      - main

jobs:
  update-date:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create version file
        run: |
          mkdir -p client/public
          echo "{\"lastUpdated\": \"$(date +'%B %d, %Y')\"}" > client/public.json

      - name: Create and Approve Pull Request
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          if [[ -n $(git status --porcelain) ]]; then
            BRANCH_NAME="update-build-date-$(date +%s)"
            git checkout -b $BRANCH_NAME
            git add client/public/version.json
            git commit -m "chore: auto-update last build date"
            git push -u origin $BRANCH_NAME
            
            PR_URL=$(gh pr create --title "chore: update build date" --body "Automatically updating the build date.")
            echo "Created PR: $PR_URL"
          else
            echo "No changes detected, skipping PR creation."
          fi