name: Update Build Date

on:
  push:
    branches:
      - main

jobs:
  update-date:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create version file
        run: |
          mkdir -p public
          echo "{\"lastUpdated\": \"$(date +'%B %d, %Y')\"}" > public/version.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: auto-update last build date"
          title: "chore: update build date"
          branch: "update-build-date"
          base: "main"
          body: "This PR automatically updates the last build date metadata."
          delete-branch: true